### ISSUE TITLE
What is the difference between patient identification and matching?

### ISSUE THREAD

**Issue by jsnichols** [standardhealth/shr#74]
> **Patient identification** is the act of being able to identify the person who is seeking or in need of care. This is not as simple as asking the patient, who may be unconscious or otherwise unable to provide accurate information, or relying on a health insurance card, which may be incorrect or fraudulent. 
> 
> **Patient matching** is the act of correctly matching a patient to his or her medical record, both within a singular healthcare entity and across entities when information needs to be shared.
> 
> Ensuring that we get patient identification right is a critical first step toward solving the problem of patient matching. **[The Chime X-Prize] is solely focused on patient identification.** There are other industry efforts underway looking at algorithms to address patient matching.

Source: [https://herox.com/PatientIDChallenge/faq](url)

**Comment by markkramerus** [comment]
I don't totally agree with the definitions above. There are three types, in my view:
1) Patient Identification. As given above, it is answering the question, who is this patient who appears before me? This is closely linked to Authentication, which is making sure the patient actually is who he or she claims to be. 
2a) Person-Record Matching. Finding the correct record, given the identification of the patient. For example, if an unconscious patient is identified by opening their wallet and getting their out their driver's license, we still have to locate their correct SHR. 
2b) Record-Record Matching. Given a bunch of records, which ones relate to the same patient? This problem may arise within a single system due to inadvertent creation of multiple records for an individual, when organizations merge, or when a record is sent from one system to another (referral or transition of care scenario). In the latter case, the record might represent a new patient to that organization, or an existing patient.

**Comment by markkramerus** [comment]
As of today, we have a good answer for matching in the SHR. Identification is usually layered on top of information systems, rather than being integrated into the system. Authentication is approached with a multi-factor approach (something you know, something you possess, perhaps also something you do (like sign your name)). It is probably layered on top, like OpenID. Closing under that assumption
